#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim,ghostty,sway,swaylock,waybar,wofi,bash"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/setup/env/
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
