#!/usr/bin/env bash

set -euo pipefail

mkdir -p "$HOME/.ssh"
cp -rfT .ssh/. "$HOME/.ssh"
gpg --decrypt ".ssh/id_rsa.gpg" > "$HOME/.ssh/id_rsa"

sudo -v

sudo pacman -Syyu --noconfirm

sudo pacman -S --needed --noconfirm \
	nvim stow tmux ghostty fzf tldr wget xclip curl git tree ripgrep fastfetch zsh \
	base-devel cmake pkgconf docker docker-compose lua unzip libtool gettext htop \
	ccache go lsof ninja python-pip moreutils clang less zig  \
	platformio-core \
	sway greetd greetd-tuigreet swaybg dmenu wofi waybar \
	brightnessctl pavucontrol grim slurp xorg-xwayland bluez-utils dosfstools sshpass \
	pulseaudio-alsa pulseaudio-bluetooth pulseaudio-equalizer pulseaudio-jack alsa-utils playerctl pacman-contrib \
	ttf-ubuntu-mono-nerd \
	ufw fail2ban 

git config --global user.name "viktorybloom" 
git config --global user.email "viktorsulejic@gmail.com"

sudo rm -rf /tmp/yay
sudo mkdir -p /tmp/yay
sudo chown -R "$USER:$USER" /tmp/yay
git clone https://aur.archlinux.org/yay-git.git /tmp/yay/yay-git
pushd /tmp/yay/yay-git
makepkg -si --noconfirm
popd

yay -S --needed --noconfirm \
	swaylock-effects autotiling

sudo tee /etc/greetd/config.toml >/dev/null <<EOF
[terminal]
vt = 1

[default_session]
command = "tuigreet --remember --cmd sway"
user = "$USER"
EOF

sudo rm -rf "$HOME/.dotfiles"
git clone --recursive git@github.com:viktorybloom/.dotfiles.git "$HOME/.dotfiles"
bash "$HOME/.dotfiles/arch"

# Harden this .....
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw --force enable

sudo tee /etc/sysctl.d/99-laptop-network-hardening.conf >/dev/null <<EOF
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
EOF

sudo sysctl --system

sudo systemctl enable --now bluetooth docker.service containerd.service fail2ban greetd


sudo groupadd -f docker
sudo usermod -aG docker "$USER"
newgrp docker

