#!/usr/bin/env bash

set -euo pipefail

sudo pacman -S --needed --noconfirm docker docker-compose
sudo groupadd docker
sudo usermod -aG docker $USER

sudo systemctl enable --now docker.service containerd.service 
