#!/usr/bin/env bash

set -euo pipefail

sudo pacman -S --needed --noconfirm ufw fail2ban 

# Harden this .....
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw --force enable

sudo tee /etc/sysctl.d/99-laptop-network-hardening.conf >/dev/null <<EOF
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
EOF

sudo sysctl --system




sudo systemctl enable --now ufw fail2ban
