# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

listener {
    timeout = 240
    on-timeout = hyprlock
}

listener {
    timeout = 260
    on-timeout = hyprctl dispatch dpms off
}

listener {
    timeout = 300
    on-timeout = systemctl suspend
}
