# Logo key. Use Mod1 for Alt.
set $mod Mod4

# Start a terminal
bindsym $mod+Return exec ghostty 

# start browser 
bindsym $mod+apostrophe exec zen-browser

# Kill focused window
bindsym $mod+q kill

# Reload the configuration file
bindsym $mod+Shift+c reload

# Application Launcher
#bindsym $mod+d exec dmenu_path | dmenu | xargs swaymsg exec --
bindsym $mod+d exec wofi --show 

# Screenshots
#bindsym Print exec --no-startup-id scrot ~/Pictures/%Y-%m-%d-%T-screenshot.png && notify-send "Screenshot saved to ~/Pictures/$(date +"%Y-%m-%d-%T")-screenshot.png"
bindsym print exec ~/.config/sway/scripts/screenshot.sh

# Exit sway (logs you out of your Wayland session)
#bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'
bindsym $mod+Shift+e exec ~/.config/sway/scripts/powermenu.sh --show

# Power Profiles menu switcher (wofi)
#bindsym $mod+Shift+p exec --no-startup-id ~/.config/i3/scripts/power-profiles

# Hibernate 
bindsym $mod+Shift+period exec systemctl suspend 

# Lock screen
bindsym $mod+Shift+x exec 'swaylock -C ~/.config/swaylock/config'

# Lid actions
bindswitch lid:on exec systemctl suspend

# Power button suspend
bindsym XF86PowerOff exec systemctl suspend

# Audio control
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioPlay exec playerctl play
bindsym XF86AudioPause exec playerctl pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous

# Brightness Control
bindsym --to-code XF86MonBrightnessUp exec brightnessctl -q set +5% # increase screen brightness
bindsym --to-code XF86MonBrightnessDown exec brightnessctl -q set 5%- # decrease screen brightness


# Touchpad control
input "1267:12693:ELAN0676:00_04F3:3195_Touchpad" {
    dwt enabled
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
}
