font pango: UbuntuMono Nerd Font 20

output * background '~/.dotfiles/wallpaper/fujinight.jpg' fill

gaps inner 15
gaps outer 7

smart_gaps on
smart_borders on

default_border pixel 2
default_floating_border pixel 2

for_window [class="^.*"] border pixel 2

hide_edge_borders smart

# class                 border   background text     indicator child_border
client.focused          #77dd77  #77dd77   #ffffff   #77dd77   #77dd77
client.unfocused        #2e3440  #2e3440   #c0c5ce   #2e3440   #2e3440
client.focused_inactive #4c566a  #4c566a   #d8dee9   #4c566a   #4c566a
client.urgent           #bf616a  #bf616a   #ffffff   #bf616a   #bf616a
